export const WIZ_SCENES = {
  35: 'Alarm',
  10: 'Bedtime',
  29: 'Candlelight',
  27: 'Christmas',
  6: 'Cozy',
  13: 'Cool white',
  12: 'Daylight',
  33: 'Diwali',
  23: 'Deep dive',
  22: 'Fall',
  5: 'Fireplace',
  7: 'Forest',
  15: 'Focus',
  30: 'Golden white',
  28: 'Halloween',
  24: 'Jungle',
  25: 'Mojito',
  14: 'Night light',
  1: 'Ocean',
  4: 'Party',
  31: 'Pulse',
  8: 'Pastel colors',
  19: 'Plantgrowth',
  2: 'Romance',
  16: 'Relax',
  36: 'Snowy sky',
  3: 'Sunset',
  20: 'Spring',
  21: 'Summer',
  32: 'Steampunk',
  17: 'True colors',
  18: 'TV time',
  34: 'White',
  9: 'Wake-up',
  11: 'Warm white',
  1000: 'Rhythm'
}
